export const LOAD_DASHBOARD_DATA = 'LOAD_DASHBOARD_DATA';
export const BEGIN_LOAD_DASHBOARD_DATA = 'BEGIN_LOAD_DASHBOARD_DATA';

export const LOADED_COURSES_DATA = 'LOAD_COURSES_DATA';
export const BEGIN_LOAD_COURSES_DATA = 'BEGIN_LOAD_COURSES_DATA';

export const LOADED_GENS_DATA = 'LOADED_GENS_DATA';
export const BEGIN_LOAD_GENS_DATA = 'BEGIN_LOAD_GENS_DATA';

export const LOADED_SEARCH_REGISTERS_DATA = 'LOADED_SEARCH_REGISTERS_DATA';
export const BEGIN_SEARCH_REGISTERS_DATA = 'BEGIN_SEARCH_REGISTERS_DATA';

export const LOAD_REGISTER_LIST_DATA = 'LOAD_REGISTER_LIST_DATA';
export const LOAD_MORE_REGISTER_LIST_DATA = 'LOAD_MORE_REGISTER_LIST_DATA';
export const BEGIN_LOAD_REGISTER_LIST_DATA = 'BEGIN_LOAD_REGISTER_LIST_DATA';

export const BEGIN_UPDATE_LOGIN_FORM = 'BEGIN_UPDATE_LOGIN_FORM';
export const UPDATED_LOGIN_FORM = 'UPDATED_LOGIN_FORM';
export const GET_USER_LOCAL = 'GET_USER_LOCAL';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOG_OUT = 'LOG_OUT';

export const BEGIN_LOAD_TABS_DATA = 'BEGIN_LOAD_TABS_DATA';
export const LOAD_TABS_DATA_SUCCESSFUL = 'LOAD_TABS_DATA_SUCCESSFUL';
export const LOAD_TABS_DATA_ERROR = 'LOAD_TABS_DATA_ERROR';
export const BEGIN_LOAD_ALL_TABS_DATA = 'BEGIN_LOAD_ALL_TABS_DATA';
export const LOAD_ALL_TABS_DATA_SUCCESSFUL = 'LOAD_ALL_TABS_DATA_SUCCESSFUL';
export const LOAD_ALL_TABS_DATA_ERROR = 'LOAD_ALL_TABS_DATA_ERROR';
export const CHANGE_CHECK_TAB = 'CHANGE_CHECK_TAB';

export const BEGIN_LOAD_STAFFS_DATA = 'BEGIN_LOAD_STAFFS_DATA';
export const LOAD_STAFFS_DATA_SUCCESSFUL = 'LOAD_STAFFS_DATA_SUCCESSFUL';
export const LOAD_STAFFS_DATA_ERROR = 'LOAD_STAFFS_DATA_ERROR';
export const BEGIN_CHANGE_ROLE_STAFF = 'BEGIN_CHANGE_ROLE_STAFF';
export const CHANGE_ROLE_STAFF_SUCCESSFUL = 'CHANGE_ROLE_STAFF_SUCCESSFUL';
export const CHANGE_ROLE_STAFF_ERROR = 'CHANGE_ROLE_STAFF_ERROR';
export const UPDATE_ADD_STAFF_FORM_DATA = 'UPDATE_ADD_STAFF_FORM_DATA';
export const UPDATE_EDIT_STAFF_FORM_DATA = 'UPDATE_EDIT_STAFF_FORM_DATA';
export const BEGIN_ADD_STAFF_DATA = 'BEGIN_ADD_STAFF_DATA';
export const ADD_STAFF_DATA_SUCCESSFUL = 'ADD_STAFF_DATA_SUCCESSFUL';
export const ADD_STAFF_DATA_ERROR = 'ADD_STAFF_DATA_ERROR';
export const BEGIN_EDIT_STAFF_DATA = 'BEGIN_EDIT_STAFF_DATA';
export const EDIT_STAFF_DATA_SUCCESSFUL = 'EDIT_STAFF_DATA_SUCCESSFUL';
export const EDIT_STAFF_DATA_ERROR = 'EDIT_STAFF_DATA_ERROR';
export const BEGIN_DELETE_STAFF_DATA = 'BEGIN_DELETE_STAFF_DATA';
export const DELETE_STAFF_DATA_SUCCESSFUL = 'DELETE_STAFF_DATA_SUCCESSFUL';
export const DELETE_STAFF_DATA_ERROR = 'DELETE_STAFF_DATA_ERROR';
export const BEGIN_CHANGE_BASE_STAFF = 'BEGIN_CHANGE_BASE_STAFF';
export const CHANGE_BASE_STAFF_SUCCESSFUL = 'CHANGE_BASE_STAFF_SUCCESSFUL';
export const CHANGE_BASE_STAFF_ERROR = 'CHANGE_BASE_STAFF_ERROR';
export const BEGIN_LOAD_STAFF_DATA = 'BEGIN_LOAD_STAFF_DATA';
export const LOAD_STAFF_DATA_SUCCESSFUL = 'LOAD_STAFF_DATA_SUCCESSFUL';
export const LOAD_STAFF_DATA_ERROR = 'LOAD_STAFF_DATA_ERROR';


export const BEGIN_LOAD_ROLES_DATA = 'BEGIN_LOAD_ROLES_DATA';
export const LOAD_ROLES_DATA_SUCCESSFUL = 'LOAD_ROLES_DATA_SUCCESSFUL';
export const LOAD_ROLES_DATA_ERROR = 'LOAD_ROLES_DATA_ERROR';
export const BEGIN_CREATE_ROLE_DATA = 'BEGIN_CREATE_ROLE_DATA';
export const CREATE_ROLE_DATA_SUCCESSFUL = 'CREATE_ROLE_DATA_SUCCESSFUL';
export const CREATE_ROLE_DATA_ERROR = 'CREATE_ROLE_DATA_ERROR';
export const CHANGE_ROLE_TITLE_FORM = 'CHANGE_ROLE_TITLE_FORM';
export const BEGIN_DELETE_ROLE_DATA = 'BEGIN_DELETE_ROLE_DATA';
export const DELETE_ROLE_DATA_SUCCESSFUL = 'DELETE_ROLE_DATA_SUCCESSFUL';
export const DELETE_ROLE_DATA_ERROR = 'DELETE_ROLE_DATA_ERROR';
export const BEGIN_LOAD_ROLE_DATA = 'BEGIN_LOAD_ROLE_DATA';
export const LOAD_ROLE_DATA_SUCCESSFUL = 'LOAD_ROLE_DATA_SUCCESSFUL';
export const LOAD_ROLE_DATA_ERROR = 'LOAD_ROLE_DATA_ERROR';
export const BEGIN_EDIT_ROLE_DATA = 'BEGIN_EDIT_ROLE_DATA';
export const EDIT_ROLE_DATA_SUCCESSFUL = 'EDIT_ROLE_DATA_SUCCESSFUL';
export const EDIT_ROLE_DATA_ERROR = 'EDIT_ROLE_DATA_ERROR';

export const BEGIN_DATA_BASE_LOAD = 'BEGIN_DATA_BASE_LOAD';
export const LOAD_DATA_BASE_SUCCESSFUL = 'LOAD_DATA_BASE_SUCCESSFUL';
export const LOAD_DATA_BASE_ERROR = 'LOAD_DATA_BASE_ERROR';
export const SELECTED_BASE_ID = 'SELECTED_BASE_ID';

export const BEGIN_LOAD_BASES = "BEGIN_LOAD_BASES";
export const LOAD_BASES_SUCCESS = "LOAD_BASES_SUCCESS";
export const SET_DEFAULT_BASE = "SET_DEFAULT_BASE";
export const UPDATE_BASE_FORM_DATA = "UPDATE_BASE_FORM_DATA";
export const BEGIN_CREATE_BASE = "BEGIN_CREATE_BASE";
export const CREATE_BASE_SUCCESS = "CREATE_BASE_SUCCESS";
export const BEGIN_LOAD_BASE = "BEGIN_LOAD_BASE";
export const LOAD_BASE_SUCCESS = "LOAD_BASE_SUCCESS";
export const DELETE_BASE_SUCCESS = "DELETE_BASE_SUCCESS";
export const RESET_CREATE_BASE_DATA = "RESET_CREATE_BASE_DATA";

export const BEGIN_LOAD_PROJECTS = "BEGIN_LOAD_PROJECTS";
export const LOAD_PROJECTS_SUCCESS = "LOAD_PROJECTS_SUCCESS";
export const UPDATE_PROJECT_FORM_DATA = "UPDATE_PROJECT_FORM_DATA";
export const RESET_CREATE_PROJECT_DATA = "RESET_CREATE_PROJECT_DATA";
export const BEGIN_CREATE_PROJECT = "BEGIN_CREATE_PROJECT";
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const BEGIN_LOAD_PROJECT = "BEGIN_LOAD_PROJECT";
export const LOAD_PROJECT_SUCCESS = "LOAD_PROJECT_SUCCESS";
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";
export const CHANGE_PROJECT_STATUS = "CHANGE_PROJECT_STATUS";


export const BEGIN_LOAD_CLIENTS = "BEGIN_LOAD_CLIENTS";
export const LOAD_CLIENTS_SUCCESS = "LOAD_CLIENTS_SUCCESS";
export const BEGIN_PING_CLIENT = "BEGIN_PING_CLIENT";
export const PING_CLIENT_SUCCESS = "PING_CLIENT_SUCCESS";
export const BEGIN_EDIT_CLIENT_TAB_DATA = "BEGIN_EDIT_CLIENT_TAB_DATA";
export const EDIT_CLIENT_TAB_DATA_SUCCESSFUL = "EDIT_CLIENT_TAB_DATA_SUCCESSFUL";
export const EDIT_CLIENT_TAB_DATA_ERROR = "EDIT_CLIENT_TAB_DATA_ERROR";
export const BEGIN_LOAD_CLIENT_TAB_DATA = "BEGIN_LOAD_CLIENT_TAB_DATA";
export const LOAD_CLIENT_TAB_DATA_SUCCESSFUL = "LOAD_CLIENT_TAB_DATA_SUCCESSFUL";
export const LOAD_CLIENT_TAB_DATA_ERROR = "LOAD_CLIENT_TAB_DATA_ERROR";
export const UPDATE_FORM_CREATE_CLIENT_DATA = "UPDATE_FORM_CREATE_CLIENT_DATA";
export const BEGIN_CREATE_CLIENT = "BEGIN_CREATE_CLIENT";
export const CREATE_CLIENT_SUCCESS = "CREATE_CLIENT_SUCCESS";
export const CHANGE_CHECK_TAB_CLIENT = "CHANGE_CHECK_TAB_CLIENT";

export const BEGIN_LOAD_CONFIGS = "BEGIN_LOAD_CONFIGS";
export const LOAD_CONFIGS_SUCCESS = "LOAD_CONFIGS_SUCCESS";
export const UPDATE_CREATE_CONFIG_FORM_DATA = "UPDATE_CREATE_CONFIG_FORM_DATA";
export const BEGIN_CREATE_CONFIG = "BEGIN_CREATE_CONFIG";
export const CREATE_CONFIG_SUCCESS = "CREATE_CONFIG_SUCCESS";
export const LOAD_CONFIG_SUCCESS = "LOAD_CONFIG_SUCCESS";
export const BEGIN_LOAD_CONFIG = "BEGIN_LOAD_CONFIG";



